using Discount.Grpc.Models;
using Microsoft.EntityFrameworkCore;

namespace Discount.Grpc.Data;

public class DiscountContext(DbContextOptions<DiscountContext> options) : DbContext(options)
{
    public DbSet<Coupon> Coupons => Set<Coupon>();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);

        modelBuilder.Entity<Coupon>(entity =>
        {
            entity.HasKey(c => c.Id);

            entity.Property(c => c.Id)
                  .UseIdentityByDefaultColumn();        // PostgreSQL GENERATED BY DEFAULT AS IDENTITY

            entity.Property(c => c.ProductName)
                  .IsRequired()
                  .HasMaxLength(100);

            entity.Property(c => c.Description)
                  .IsRequired()
                  .HasMaxLength(500)
                  .HasDefaultValue(string.Empty);

            entity.Property(c => c.Amount)
                  .HasColumnType("double precision")
                  .HasDefaultValue(0.0);

            // ── Seed data (applied by migration, sequence is reset automatically) ──
            entity.HasData(
                new Coupon { Id = 1, ProductName = "IPhone X",   Description = "IPhone Discount",  Amount = 150 },
                new Coupon { Id = 2, ProductName = "Samsung 10", Description = "Samsung Discount", Amount = 100 }
            );
        });
    }
}

